### PR TITLE
numpy ndarray support

### PR DESCRIPTION
**Pull request by diegojromerolopez**

### CODE REVIEW

**Comment by julian-goettingen** [comment]
any update on this? It seems like a wonderful feature.

**Comment by julian-goettingen** [comment]
absolutely awesome to see you revive this after so long!
In the project I wanted to use this I have used another solution to my original problem, since noticing python-level-write-access to the array is insufficient - the mutations happen in libraries.

But I still think this project is very cool.

**Comment by diegojromerolopez** [comment]
@julian-goettingen thank you for your kind words. At this point I have not set a donations platform, maybe I'll do it in the future.

Could you take a look at this PR and see if it fits your needs?

**Comment by julian-goettingen** [comment]
A problem I would not know how to solve is that numpy arrays are typically mutated outside of the python-interpreter. Any C-extension of python may receive a pointer to the raw data of the array and perform read/write operations on it without triggering any python-code such as dunder-setindex. The frozen array would somehow have to detect it is being used as part of a method-call and wrap that call somehow to check if it was modified - I do not think that is possible even though I am often surprised by what is possible in python.

However, what libraries _typically_ do is to treat the contents of the array as immutable and return a new array to store the result. These library calls may be used to mutate instance variables (think of self.x=self.x+a or something) which this library could detect now which is fantastic.

**Comment by julian-goettingen** [comment]
I just realized you used a special numpy-flag to make the array unwritable. This is much smarter than I thought, I thought you just intercepted dunder-setindex. Since it is also a copy, I no longer see any way this could lead to accidental modifications when using well-behaved libraries. Very cool.

**Comment by diegojromerolopez** [comment]
Thank you @julian-goettingen, let's see how this feature behaves in the wild!

**Pull request merged**
